# Generated by Django 5.2.7 on 2025-10-19 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_name', models.CharField(max_length=100)),
                ('reminder_description', models.TextField(blank=True, max_length=500)),
                ('reminder_start_date', models.DateField()),
                ('reminder_end_date', models.DateField()),
                ('reminder_time_between', models.TimeField()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
