# Generated by Django 5.2.7 on 2025-10-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reminders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reminders',
            new_name='Reminder',
        ),
    ]
