# Generated by Django 5.2.7 on 2025-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_reminders_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_end_date',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_time_between',
            field=models.DurationField(),
        ),
    ]
